spring:
  cloud:
    stream:
      bindings:
        register-user-in:
          destination: register.user.out
          binder: rabbit1
        register-user-ex:
          destination: register.user.out2
          binder: rabbit1
        login-user-in:
          destination: login.user.out
          binder: rabbit1
        login-user-out:
          destination: login.user.out2
          binder: rabbit1
        get-user-out:
          destination: get.user.out2
          binder: rabbit1
        get-user-in:
          destination: get.user.out
          binder: rabbit1
        change-user-out:
          destination: change.user.out2
          binder: rabbit1
        change-user-in:
          destination: change.user.out
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                
server:  
  port: ${PORT:2224}