spring:
  cloud:
    stream:
      bindings:
        register-in:
          destination: stream.register
          group: user
          binder: rabbit1
        output:
          destination: ex.stream.out2
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                
server:  
  port: ${PORT:2224}