spring:
  cloud:
    stream:
      bindings:
        add-cart-in:
          destination: add.cart.out
          group: inventory
          binder: rabbit1
        added-cart-out:
          destination: added.cart.out
          binder: rabbit1
        add-cart-ex:
          destination: add.cart.out2
          binder: rabbit1
        request-inv-in:
          destination: request.inv.out
          binder: rabbit1
        request-inv-out:
          destination: request.inv.out2
          binder: rabbit1
        request-cart-in:
          destination: request.cart.out2
          binder: rabbit1
        request-cart-out:
          destination: request.cart.out3
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                
server:  
  port: ${PORT:2226}